// === styleFinderData.js ===
// Contains data structures for the Style Finder feature.

// Style categories
export const sfStyles = {
  submissive: [
    'Submissive', 'Brat', 'Slave', 'Switch', 'Pet', 'Little', 'Puppy', 'Kitten', 'Princess', 'Rope Bunny',
    'Masochist', 'Prey', 'Toy', 'Doll', 'Bunny', 'Servant', 'Playmate', 'Babygirl', 'Captive', 'Thrall',
    'Puppet', 'Maid', 'Painslut', 'Bottom'
  ],
  dominant: [
    'Dominant', 'Assertive', 'Nurturer', 'Strict', 'Master', 'Mistress', 'Daddy', 'Mommy', 'Owner', 'Rigger',
    'Sadist', 'Hunter', 'Trainer', 'Puppeteer', 'Protector', 'Disciplinarian', 'Caretaker', 'Sir', 'Goddess', 'Commander'
  ]
};

// Submissive traits (Randomization happens in app.js)
export const sfSubFinderTraits = [
  { name: 'obedience', desc: 'How much do you enjoy following instructions or rules given by someone you trust?' },
  { name: 'rebellion', desc: 'Do you find it fun to playfully resist or tease when someone tries to guide you?' },
  { name: 'service', desc: 'Does it feel rewarding to assist or do tasks that make someone else happy?' },
  { name: 'playfulness', desc: 'How much do you love engaging in silly games or lighthearted mischief?' },
  { name: 'sensuality', desc: 'Do soft touches, textures, or physical sensations light up your senses?' },
  { name: 'exploration', desc: 'Are you excited by the idea of trying new experiences or stepping into the unknown?' },
  { name: 'devotion', desc: 'Does being deeply loyal and committed to someone bring you a sense of fulfillment?' },
  { name: 'innocence', desc: 'Do you enjoy feeling carefree, pure, or even a bit childlike in your interactions?' },
  { name: 'mischief', desc: 'How much do you like stirring things up with a cheeky prank or playful trouble?' },
  { name: 'affection', desc: 'Do you crave physical closeness, like hugs or cuddles, to feel connected?' },
  { name: 'painTolerance', desc: 'Does a little sting or discomfort excite you, or do you prefer to avoid it?' },
  { name: 'submissionDepth', desc: 'How much do you enjoy letting go completely and giving someone full control?' },
  { name: 'dependence', desc: 'Do you feel comforted and secure when you can rely on someone else to guide you?' },
  { name: 'vulnerability', desc: 'Does opening up emotionally and being exposed feel natural and right to you?' },
  { name: 'adaptability', desc: 'How easily can you switch between different roles or adjust to new expectations?' },
  { name: 'tidiness', desc: 'Do you take pride in keeping things neat, clean, and perfectly organized for someone?' },
  { name: 'politeness', desc: 'Does being courteous and respectful in your actions come naturally to you?' },
  { name: 'craving', desc: 'Do you actively seek out intense sensations or experiences that push your limits?' },
  { name: 'receptiveness', desc: 'How open are you to receiving direction, sensations, or guidance from someone else?' }
];

// Submissive trait footnotes
export const sfSubTraitFootnotes = {
  obedience: "1: Rarely follows / 10: Always obeys",
  rebellion: "1: Very compliant / 10: Loves to resist",
  service: "1: Self-focused / 10: Service-driven",
  playfulness: "1: Serious / 10: Super playful",
  sensuality: "1: Not sensory / 10: Highly sensual",
  exploration: "1: Stays safe / 10: Seeks adventure",
  devotion: "1: Independent / 10: Deeply devoted",
  innocence: "1: Mature / 10: Very innocent",
  mischief: "1: Calm / 10: Mischievous",
  affection: "1: Distant / 10: Super affectionate",
  painTolerance: "1: Avoids pain / 10: Loves pain",
  submissionDepth: "1: Light submission / 10: Total surrender",
  dependence: "1: Self-reliant / 10: Loves guidance",
  vulnerability: "1: Guarded / 10: Fully open",
  adaptability: "1: Fixed role / 10: Very versatile",
  tidiness: "1: Messy and carefree / 10: Obsessed with order",
  politeness: "1: Casual and blunt / 10: Always courteous",
  craving: "1: Avoids intensity / 10: Seeks extreme thrills",
  receptiveness: "1: Closed off / 10: Fully open to input"
};

// Dominant traits (Randomization happens in app.js)
export const sfDomFinderTraits = [
  { name: 'authority', desc: 'Do you feel strong when you take charge?' },
  { name: 'confidence', desc: 'Are you sure of your decisions?' },
  { name: 'discipline', desc: 'Do you enjoy setting firm rules?' },
  { name: 'boldness', desc: 'Do you dive into challenges fearlessly?' },
  { name: 'care', desc: 'Do you love supporting and protecting others?' },
  { name: 'empathy', desc: 'Do you tune into others’ feelings easily?' },
  { name: 'control', desc: 'Do you thrive on directing every detail?' },
  { name: 'creativity', desc: 'Do you enjoy crafting unique scenes?' },
  { name: 'precision', desc: 'Are you careful with every step you take?' },
  { name: 'intensity', desc: 'Do you bring fierce energy to what you do?' },
  { name: 'sadism', desc: 'Does giving a little pain excite you?' },
  { name: 'leadership', desc: 'Do you naturally guide others forward?' },
  { name: 'possession', desc: 'Do you feel pride in owning what’s yours?' },
  { name: 'patience', desc: 'Are you calm while teaching or training?' },
  { name: 'dominanceDepth', desc: 'Do you crave total power in a scene?' }
];

// Dominant trait footnotes
export const sfDomTraitFootnotes = {
  authority: "1: Gentle / 10: Very commanding",
  confidence: "1: Hesitant / 10: Rock-solid",
  discipline: "1: Relaxed / 10: Strict",
  boldness: "1: Cautious / 10: Fearless",
  care: "1: Detached / 10: Deeply caring",
  empathy: "1: Distant / 10: Highly intuitive",
  control: "1: Hands-off / 10: Total control",
  creativity: "1: Routine / 10: Very creative",
  precision: "1: Casual / 10: Meticulous",
  intensity: "1: Soft / 10: Intense",
  sadism: "1: Avoids pain / 10: Enjoys giving pain",
  leadership: "1: Follower / 10: Natural leader",
  possession: "1: Shares / 10: Very possessive",
  patience: "1: Impatient / 10: Very patient",
  dominanceDepth: "1: Light control / 10: Full dominance"
};

// Slider descriptions for each trait
export const sfSliderDescriptions = {
  obedience: [ "You dodge orders like a breeze!", "Rules? You’re too free for that!", "You’ll follow if it’s fun!", "A little “yes” slips out sometimes!", "You’re cool with gentle guidance!", "Following feels kinda nice!", "You like pleasing when asked!", "Obeying’s your quiet joy!", "You love a sweet “please”!", "You glow when you say “yes”!" ],
  rebellion: [ "You’re too sweet to say no!", "A tiny “nah” sneaks out!", "You nudge rules with a smile!", "Teasing’s your little game!", "Half yes, half no—cute!", "You push back with charm!", "Defiance is your sparkle!", "You love a playful “no”!", "Rebel vibes all the way!", "You’re a cheeky star!" ],
  service: [ "Helping? You’re too chill!", "A quick favor’s enough!", "You help if they’re sweet!", "You pitch in when it’s easy!", "Serving’s okay sometimes!", "You like making them smile!", "Helping’s your happy place!", "You love a kind task!", "You’re a service sweetie!", "Caring’s your superpower!" ],
  playfulness: [ "Serious is your vibe!", "A giggle slips out!", "You play if it’s light!", "Half serious, half silly!", "You’re warming up to fun!", "Playtime’s your joy!", "You bounce with glee!", "Silly’s your middle name!", "You’re a playful whirlwind!", "Games are your world!" ],
  sensuality: [ "Touch? Not your thing!", "A soft pat’s okay!", "You like a little feel!", "Textures are kinda neat!", "You’re into soft vibes!", "Silk makes you happy!", "You love a sensory tickle!", "Touch is your bliss!", "You’re all about feels!", "Sensory queen!" ],
  exploration: [ "Safe is your spot!", "A tiny step out—shy!", "You peek at new stuff!", "You’ll try if it’s safe!", "Half cozy, half curious!", "New things excite you!", "You chase the unknown!", "Adventure’s your jam!", "You’re a bold explorer!", "Nothing stops you!" ],
  devotion: [ "Free and solo!", "A bit of heart shows!", "You care if they’re near!", "Half free, half true!", "You’re warming up!", "Devotion’s your glow!", "You’re all in soft!", "Loyalty’s your core!", "You’re a devotion gem!", "Total soulmate!" ],
  innocence: [ "Wise beyond your years!", "A bit of wonder peeks out!", "You’re half grown, half kid!", "Silly feels nice sometimes!", "You’re dipping into cute!", "Innocence is your vibe!", "You’re a sweet dreamer!", "Giggles are your song!", "You’re pure sunshine!", "Total kid at heart!" ],
  mischief: [ "Too good for tricks!", "A tiny prank slips!", "You stir if it’s safe!", "Half calm, half cheeky!", "You’re a sneaky spark!", "Mischief’s your game!", "You love a little chaos!", "Trouble’s your friend!", "You’re a mischief pro!", "Chaos queen!" ],
  affection: [ "Hugs? Not really!", "A quick cuddle’s fine!", "You like a soft touch!", "Half aloof, half warm!", "You’re into snuggles!", "Cuddles are your joy!", "You love closeness!", "Affection’s your glow!", "You’re a hug star!", "Total love bug!" ],
  painTolerance: [ "Ouch! Prefer gentle.", "A little sting is okay.", "Can handle moderate spice.", "Intensity feels interesting.", "Bring on the challenge!", "Thriving on the edge.", "Pushing my limits!", "Pain can be pleasure.", "Craving strong sensations!", "Almost limitless tolerance!" ], // Corrected Pain Tolerance Descriptions
  submissionDepth: [ "You’re free as a bird!", "A little give peeks out!", "You bend if it’s chill!", "Half you, half them!", "You’re easing in!", "Surrender’s kinda fun!", "You dive in soft!", "Control’s theirs—yay!", "You’re all theirs!", "Total trust star!" ],
  dependence: [ "Solo’s your jam!", "A lean slips in!", "You lean if they’re nice!", "Half free, half clingy!", "You’re okay with help!", "Relying feels good!", "You love their lead!", "They’re your rock!", "You’re a lean-in pro!", "Total trust buddy!" ],
  vulnerability: [ "Walls up high!", "A peek slips out!", "You share if safe!", "Half guarded, half open!", "You’re softening up!", "Open’s your vibe!", "You bare it soft!", "Heart’s wide open!", "You’re a trust gem!", "Total soul sharer!" ],
  adaptability: [ "One way—you’re set!", "A tiny switch is fine!", "You bend a little!", "Half fixed, half fluid!", "You’re okay with change!", "Switching’s easy!", "You roll with it!", "Flex is your strength!", "You flip like a pro!", "Total chameleon!" ],
  tidiness: [ "Chaos is your friend!", "A little mess is fine!", "You tidy if asked nicely!", "Order’s okay sometimes!", "You like things neat-ish!", "Cleanliness feels good!", "You love a tidy space!", "Order is your joy!", "Spotless is your vibe!", "Perfection in every corner!" ],
  politeness: [ "You’re blunt and bold!", "A bit gruff but sweet!", "Polite if it’s easy!", "You’re nice when needed!", "Courtesy’s your thing!", "You’re a polite gem!", "Manners shine bright!", "Respect is your core!", "You’re super courteous!", "Politeness queen!" ],
  craving: [ "Calm is your zone!", "A tiny thrill is enough!", "You dip into intensity!", "Half chill, half wild!", "You like a strong spark!", "Intensity calls you!", "You chase the edge!", "Thrills are your fuel!", "You crave the extreme!", "Limitless seeker!" ],
  receptiveness: [ "You’re your own guide!", "A bit open if safe!", "You listen if it’s clear!", "Half closed, half open!", "You’re warming up!", "Openness feels right!", "You take it all in!", "Guidance is welcome!", "You’re a receiver pro!", "Totally in tune!" ],
  authority: [ "Soft and shy!", "A little lead peeks!", "You guide if asked!", "Half gentle, half firm!", "You’re stepping up!", "Authority’s your vibe!", "You lead with ease!", "You’re a strong guide!", "Boss mode on!", "Total commander!" ],
  confidence: [ "Quiet and unsure!", "A bit of bold shows!", "You’re sure if it’s easy!", "Half shy, half steady!", "You’re growing bold!", "Confidence shines!", "You trust your gut!", "You’re rock solid!", "Bold and bright!", "Total powerhouse!" ],
  discipline: [ "Free and wild!", "A rule slips in!", "You set soft lines!", "Half loose, half tight!", "You’re liking order!", "Discipline’s your jam!", "You keep it firm!", "Rules are your strength!", "You’re super strict!", "Total control!" ],
  boldness: [ "Careful and calm!", "A risk peeks out!", "You leap if safe!", "Half shy, half daring!", "You’re getting brave!", "Boldness is you!", "You dive right in!", "Fearless vibes!", "You’re a bold star!", "Total daredevil!" ],
  care: [ "Cool and aloof!", "A care slips out!", "You help if asked!", "Half chill, half warm!", "You’re a soft guide!", "Nurturing’s your glow!", "You protect with love!", "Care is your core!", "You’re a warm star!", "Total nurturer!" ],
  empathy: [ "Distant and chill!", "A feel peeks out!", "You get it if clear!", "Half aloof, half tuned!", "You’re sensing more!", "Empathy’s your gift!", "You feel it all!", "You’re in sync!", "You’re a heart reader!", "Total intuitive!" ],
  control: [ "Hands-off feels right.", "Suggesting is fine.", "Guiding the flow.", "Like directing details.", "Enjoy orchestration.", "Precise scene control.", "Need full command.", "Every detail is mine.", "Total control feels best.", "Absolute micro-manager!" ], // Corrected Control Descriptions
  creativity: [ "Simple’s your way!", "A spark pops up!", "You craft if quick!", "Half plain, half wild!", "You’re sparking up!", "Creativity flows!", "You make magic!", "Ideas are your joy!", "You’re a vision star!", "Total creator!" ],
  precision: [ "Loose and free!", "A bit neat’s fine!", "You care if fast!", "Half sloppy, half sharp!", "You’re getting exact!", "Precision’s your thing!", "You nail it all!", "Every step’s perfect!", "You’re a detail whiz!", "Total master!" ],
  intensity: [ "Soft and mellow!", "A flare sneaks out!", "You heat if safe!", "Half calm, half fierce!", "You’re turning up!", "Intensity’s your spark!", "You bring the blaze!", "Fierce is your vibe!", "You’re a fire star!", "Total storm!" ],
  sadism: [ "Soft and sweet!", "A tease slips in!", "You push a little!", "Half gentle, half wild!", "You’re testing it!", "Pain’s your play!", "You love the sting!", "Thrill’s your game!", "You’re a spicy star!", "Total edge master!" ],
  leadership: [ "Soft and shy!", "A lead peeks out!", "You guide if asked!", "Half gentle, half firm!", "You’re stepping up!", "Leading’s your vibe!", "You steer with ease!", "You’re a bold guide!", "Leader mode on!", "Total captain!" ],
  possession: [ "Free and open!", "A claim slips out!", "You hold if sweet!", "Half share, half mine!", "You’re liking it!", "Possession’s your vibe!", "You claim with pride!", "Yours is yours!", "You’re a keeper!", "Total owner!" ],
  patience: [ "Fast and now!", "A wait slips in!", "You chill if quick!", "Half rush, half calm!", "You’re cooling down!", "Patience is you!", "You wait with grace!", "Calm’s your strength!", "You’re a zen star!", "Total peace!" ],
  dominanceDepth: [ "Light and free!", "A hold peeks out!", "You lead if easy!", "Half soft, half firm!", "You’re taking charge!", "Power’s your glow!", "You rule with ease!", "Control’s your core!", "You’re a power gem!", "Total ruler!" ]
};

// Trait explanations for info popups
export const sfTraitExplanations = {
  obedience: "This explores how much you enjoy following instructions or rules. Do you feel calm and happy when told what to do, or prefer your own thing?",
  rebellion: "How much do you like to playfully resist or tease when given orders? Do you enjoy back-and-forth?",
  service: "How much joy do you get from helping others? Do tasks like fetching or assisting feel rewarding?",
  playfulness: "How much do you love silly, lighthearted fun? Are you serious, or do games/giggles light you up?",
  sensuality: "How much do physical sensations (soft touches, textures) excite you? Do you crave them?",
  exploration: "Checks your eagerness for new things. Comfy sticking to the known, or jump at experiments?",
  devotion: "How deeply loyal do you feel? Stick by them no matter what, or like independence?",
  innocence: "Enjoying a carefree, childlike vibe. Mature/serious, or love feeling sweet/playful?",
  mischief: "Enjoy stirring things up? Calm/good, or love a cheeky prank?",
  affection: "How much do you crave closeness/cuddles? Hugs your thing, or prefer space?",
  painTolerance: "How do you feel about discomfort/sting? Does it excite you, or do you shy away?",
  submissionDepth: "How much control are you happy giving up? Light guidance, or totally letting go?",
  dependence: "Feel safe relying on someone else? Independent, or love leaning on others?",
  vulnerability: "Comfy opening up emotionally? Guard up, or share your heart easily?",
  adaptability: "How easily do you switch roles/moods? Set one way, or flow with changes?",
  tidiness: "Enjoy keeping things neat for someone? Satisfaction in spotless, or happier a bit wild?",
  politeness: "Naturally lean toward courteous/respectful? Manners important, or prefer casual/direct?",
  craving: "How much do you seek intense/extreme experiences? Pulled to push boundaries, or prefer gentle/calm?",
  receptiveness: "How open are you to direction/sensations? Welcome guidance/input, or steer your own course?",
  authority: "How natural is taking charge? Love leading, or prefer softer approach?",
  confidence: "How sure are you in choices? Bold/steady, or hesitate sometimes?",
  discipline: "Enjoy setting rules? Like structure, or more relaxed?",
  boldness: "How fearless are you? Dive into challenges, or take it slow?",
  care: "Love supporting others? Nurturing type, or more hands-off?",
  empathy: "Tune into others’ feelings? Feel what they feel, or keep distance?",
  control: "Thrive on directing things? Love being in charge, or let things flow?",
  creativity: "Enjoy crafting unique ideas? Imaginative, or stick to basics?",
  precision: "Careful with details? Plan every step, or go with the vibe?",
  intensity: "Fierce energy you bring? Calm, or burn bright?",
  sadism: "Giving a little pain excite you? Fun for you, or not your thing?",
  leadership: "Guiding others naturally? Lead the way, or step back?",
  possession: "Feel pride in ‘owning’? Possessive, or easygoing?",
  patience: "Calm teaching/waiting? Chill, or push fast?",
  dominanceDepth: "How much power do you crave? Light control, or total command?"
};

// Style descriptions with short, long, and tips
export const sfStyleDescriptions = {
  Submissive: { short: "Thrives on guidance, loves letting others lead.", long: "Finds joy in yielding, savoring peace from trust/structure. Embraces vulnerability, finds strength in surrender.", tips: ["Communicate limits.", "Find respectful partner.", "Explore submission levels."] },
  Brat: { short: "Cheeky, loves pushing buttons for fun!", long: "Delights in playful resistance, turning rules into wit/charm games. Thrill of chase, joy of 'taming'.", tips: ["Keep it fun.", "Pair with chaser.", "Set defiance boundaries."] },
  Slave: { short: "Fulfilled by total devotion & service.", long: "Deeply committed, embraces high control/structure. Needs immense trust/communication.", tips: ["Negotiate limits.", "Ensure partner values devotion.", "Prioritize self-care."] },
  Switch: { short: "Flows between leading/following.", long: "Enjoys both worlds, adapts easily. Versatile, playful, thrives on exploration.", tips: ["Communicate mood.", "Experiment both roles.", "Find flexible partners."] },
  Pet: { short: "Loves being cared for like cherished companion.", long: "Revels in affection/play, often animal-like traits. Loyalty & fun.", tips: ["Choose persona.", "Seek caring Owner.", "Enjoy role freedom."] },
  Little: { short: "Embraces carefree, childlike spirit.", long: "Finds joy in innocence/dependence, seeks nurturing/protection.", tips: ["Set boundaries.", "Find caring partner.", "Explore playful side."] },
  Puppy: { short: "Playful, loyal, devoted pup.", long: "Boundless energy/affection, thrives on play/devotion.", tips: ["Embrace enthusiasm.", "Seek Trainer/Owner.", "Keep fun & safe."] },
  Kitten: { short: "Sensual, mischievous, curious cat.", long: "Blends sensuality/mischief, enjoys affection/play, tender/teasing.", tips: ["Play with charm.", "Find patient partner.", "Explore senses."] },
  Princess: { short: "Adores being pampered & adored.", long: "Revels in attention/care, regal yet dependent, innocence/sensuality.", tips: ["Set expectations.", "Seek doting partner.", "Enjoy spotlight."] },
  'Rope Bunny': { short: "Loves the art & feel of being bound.", long: "Excitement in sensations/trust of bondage, enjoys creativity/surrender.", tips: ["Learn safety.", "Pair with skilled Rigger.", "Explore ties."] },
  Masochist: { short: "Finds pleasure in the thrill of pain.", long: "Embraces discomfort as joy, often with submission. Trust/intensity.", tips: ["Set safewords.", "Find caring Sadist.", "Know limits."] },
  Prey: { short: "Enjoys the thrill of being hunted.", long: "Thrives on chase, excitement in vulnerability, tension of pursuit/capture.", tips: ["Clear consent.", "Pair with Hunter.", "Enjoy adrenaline."] },
  Toy: { short: "Loves being used & played with.", long: "Delights as object of pleasure, adaptable/submissive. Control/fun.", tips: ["Communicate prefs.", "Find creative partner.", "Embrace role."] },
  Doll: { short: "Enjoys being shaped & admired.", long: "Fulfilled by molding/display, vulnerability/desire to please/be perfect.", tips: ["Set boundaries.", "Seek Puppeteer.", "Enjoy transformation."] },
  Bunny: { short: "Playful & sweet like a rabbit.", long: "Innocence/energy, thrives on affection/light play.", tips: ["Keep fun.", "Find gentle partner.", "Hop into role."] },
  Servant: { short: "Finds joy in serving & pleasing.", long: "Dedicated to partner’s needs, satisfaction in obedience/tasks.", tips: ["Define duties.", "Seek Master/Mistress.", "Balance service/self-care."] },
  Playmate: { short: "Loves sharing fun & mischief.", long: "Camaraderie/adventure, enjoys games/exploration.", tips: ["Keep light.", "Find playful partner.", "Explore together."] },
  Babygirl: { short: "Craves nurturing & affection.", long: "Blends innocence/dependence, seeks caring dynamic.", tips: ["Set emotional boundaries.", "Find Daddy/Mommy.", "Embrace softness."] },
  Captive: { short: "Relishes thrill of being held.", long: "Enjoys intensity of surrender/restraint, excitement in control/trust.", tips: ["Negotiate scenes.", "Pair with Hunter.", "Enjoy intensity."] },
  Thrall: { short: "Bound by deep devotion.", long: "Complete loyalty/submission, profound trust/surrender.", tips: ["Build trust slowly.", "Seek Master.", "Honor commitment."] },
  Puppet: { short: "Loves being directed precisely.", long: "Thrives on responsiveness, moves to cues. Fluidity/trust.", tips: ["Stay attuned.", "Find flexible Puppeteer.", "Practice responses."] },
  Maid: { short: "Delights in tidy, polite service.", long: "Joy in order/courtesy, pristine environment. Service/refinement.", tips: ["Focus on details.", "Seek polish-appreciator.", "Balance duty/grace."] },
  Painslut: { short: "Craves intense pain, pushes limits.", long: "Seeks strong sensations, exhilaration in discomfort. Bold/boundary-testing.", tips: ["Set pain thresholds.", "Pair with respectful Sadist.", "Embrace aftercare."] },
  Bottom: { short: "Open to receiving sensation/direction.", long: "Excels at taking input, stamina for long scenes. Receptive/resilient.", tips: ["Communicate capacity.", "Find endurance-valuer.", "Pace yourself."] },
  Dominant: { short: "Shines in charge, guides confidently.", long: "Revels in control, leads with strength/care. Responsibility/trust.", tips: ["Listen to partner.", "Balance firm/kind.", "Learn safety."] },
  Assertive: { short: "Leads with bold, decisive energy.", long: "Takes charge confidently/intensely, authority shapes scene.", tips: ["Be direct.", "Pair with Submissive.", "Temper boldness."] },
  Nurturer: { short: "Guides with warmth & care.", long: "Blends control/empathy, guidance feels like warm embrace. Support/growth.", tips: ["Be patient/attentive.", "Pair with Little/Pet.", "Foster trust/safety."] },
  Strict: { short: "Enforces rules precisely.", long: "Maintains order/discipline, satisfaction in structure/obedience. Firm but fair.", tips: ["Set expectations.", "Pair with Slave/Servant.", "Reward compliance."] },
  Master: { short: "Leads with authority & responsibility.", long: "Profound role, guides with control/care/commitment. Structured/trusting.", tips: ["Build trust.", "Understand needs.", "Negotiate terms."] },
  Mistress: { short: "Commands with grace & power.", long: "Leads confidently/creatively, blends sensuality/control. Elegant/intense.", tips: ["Embrace power.", "Pair with Slave/Toy.", "Explore creative control."] },
  Daddy: { short: "Protects & nurtures with firm hand.", long: "Blends care/authority, guidance/structure. Loving/firm.", tips: ["Be consistent.", "Pair with Little/Babygirl.", "Balance discipline/affection."] },
  Mommy: { short: "Nurtures & guides with warmth.", long: "Blend of care/control, safe space to explore/grow.", tips: ["Be patient/loving.", "Pair with Little/Pet.", "Encourage growth."] },
  Owner: { short: "Pride in possessing & caring.", long: "Fulfillment in control/responsibility, pet play/TPE.", tips: ["Set rules.", "Pair with Pet/Slave.", "Provide structure/care."] },
  Rigger: { short: "Artist of restraint & sensation.", long: "Excels in bondage art, intricate ties. Creativity/control/trust.", tips: ["Learn safety.", "Pair with Rope Bunny.", "Explore styles."] },
  Sadist: { short: "Joy in giving pain with care.", long: "Enjoys inflicting discomfort (consensually). Intensity/connection.", tips: ["Negotiate limits.", "Pair with Masochist.", "Prioritize aftercare."] },
  Hunter: { short: "Thrives on chase & capture.", long: "Enjoys dynamic tension of pursuit, thrill of hunt/surrender.", tips: ["Establish consent.", "Pair with Prey.", "Enjoy the game."] },
  Trainer: { short: "Guides with patience & structure.", long: "Focuses on teaching/molding partner, behavior mod/skill dev.", tips: ["Be clear/consistent.", "Pair with Pet/Slave.", "Celebrate progress."] },
  Puppeteer: { short: "Controls with creative precision.", long: "Enjoys directing every move, partner as extension of will.", tips: ["Communicate clearly.", "Pair with Doll/Toy.", "Explore vision."] },
  Protector: { short: "Leads with strength & care.", long: "Blends authority/responsibility, ensures partner feels safe/valued.", tips: ["Be vigilant/kind.", "Pair with Little/Pet.", "Foster trust."] },
  Disciplinarian: { short: "Enforces rules firmly, fairly.", long: "Excels at boundaries/order, enjoys guiding playful/resistant partner.", tips: ["Clear rules.", "Patient/fair.", "Reward compliance."] },
  Caretaker: { short: "Nurtures & supports with love.", long: "Provides safe, loving space for exploration (age/pet play).", tips: ["Attentive/gentle.", "Pair with Little/Pet.", "Encourage exploration."] },
  Sir: { short: "Leads with honor & respect.", long: "Commands with authority/integrity, values tradition/structure.", tips: ["Uphold values.", "Pair with Submissive/Slave.", "Lead by example."] },
  Goddess: { short: "Worshipped & adored.", long: "Embodies power/grace, partner offers devotion/service.", tips: ["Embrace divinity.", "Pair with Thrall/Servant.", "Set high standards."] },
  Commander: { short: "Leads with strategic control.", long: "Takes charge precisely/vision, complex scenes/TPE.", tips: ["Plan carefully.", "Pair with Switch/Submissive.", "Execute confidently."] }
};

// Dynamic matches for each style
export const sfDynamicMatches = {
  Submissive: { dynamic: "Power Exchange", match: "Dominant", desc: "Classic duo.", longDesc: "Mutual respect, clear roles." },
  Brat: { dynamic: "Taming Play", match: "Disciplinarian", desc: "Sparks fly!", longDesc: "Resistance meets control." },
  Slave: { dynamic: "Master/Slave", match: "Master", desc: "Deep trust.", longDesc: "Devotion & structure." },
  Switch: { dynamic: "Versatile Play", match: "Switch", desc: "Fluid power.", longDesc: "Explore both sides." },
  Pet: { dynamic: "Pet Play", match: "Owner", desc: "Playful care.", longDesc: "Affection & playfulness." },
  Little: { dynamic: "Age Play", match: "Caretaker", desc: "Nurturing space.", longDesc: "Care & trust." },
  Puppy: { dynamic: "Pup Play", match: "Trainer", desc: "Lively bond.", longDesc: "Energy & discipline." },
  Kitten: { dynamic: "Kitten Play", match: "Owner", desc: "Sensual connection.", longDesc: "Charm & control." },
  Princess: { dynamic: "Pampering Play", match: "Daddy", desc: "Regal care.", longDesc: "Spoiling & structure." },
  'Rope Bunny': { dynamic: "Bondage Play", match: "Rigger", desc: "Artistic exchange.", longDesc: "Trust & creativity." },
  Masochist: { dynamic: "Sadomasochism", match: "Sadist", desc: "Thrilling exchange.", longDesc: "Pain & pleasure." },
  Prey: { dynamic: "Primal Play", match: "Hunter", desc: "Wild chase.", longDesc: "Pursuit & surrender." },
  Toy: { dynamic: "Objectification Play", match: "Owner", desc: "Playful use.", longDesc: "Control & adaptability." },
  Doll: { dynamic: "Transformation Play", match: "Puppeteer", desc: "Creative shaping.", longDesc: "Molding & trust." },
  Bunny: { dynamic: "Bunny Play", match: "Caretaker", desc: "Sweet bond.", longDesc: "Innocence & care." },
  Servant: { dynamic: "Service Play", match: "Master", desc: "Structured duty.", longDesc: "Guidance & harmony." },
  Playmate: { dynamic: "Adventure Play", match: "Playmate", desc: "Shared journey.", longDesc: "Fun & exploration." },
  Babygirl: { dynamic: "Age Play", match: "Daddy", desc: "Nurturing space.", longDesc: "Love & protection." },
  Captive: { dynamic: "Captivity Play", match: "Hunter", desc: "Intense thrill.", longDesc: "Control & surrender." },
  Thrall: { dynamic: "Devotion Play", match: "Goddess", desc: "Deep worship.", longDesc: "Loyalty & power." },
  Puppet: { dynamic: "Puppet Play", match: "Puppeteer", desc: "Controlled dance.", longDesc: "Adaptability & direction." },
  Maid: { dynamic: "Service Play", match: "Mistress", desc: "Refined duty.", longDesc: "Tidiness & elegance." },
  Painslut: { dynamic: "Sadomasochism", match: "Sadist", desc: "Fiery intensity.", longDesc: "Craving & skill." },
  Bottom: { dynamic: "Sensation Play", match: "Dominant", desc: "Steady flow.", longDesc: "Receptiveness & authority." },
  Dominant: { dynamic: "Power Exchange", match: "Submissive", desc: "Balanced duo.", longDesc: "Guidance & trust." },
  Assertive: { dynamic: "Assertive Control", match: "Submissive", desc: "Bold exchange.", longDesc: "Authority shapes bond." },
  Nurturer: { dynamic: "Nurturing Care", match: "Little", desc: "Warm bond.", longDesc: "Care fosters growth." },
  Strict: { dynamic: "Discipline Play", match: "Slave", desc: "Firm bond.", longDesc: "Order & obedience." },
  Master: { dynamic: "Master/Slave", match: "Slave", desc: "Deep relationship.", longDesc: "Authority & devotion." },
  Mistress: { dynamic: "Mistress/Servant", match: "Servant", desc: "Elegant bond.", longDesc: "Grace & service." },
  Daddy: { dynamic: "Daddy/Little", match: "Little", desc: "Nurturing bond.", longDesc: "Care & play." },
  Mommy: { dynamic: "Mommy/Little", match: "Little", desc: "Loving bond.", longDesc: "Warmth & growth." },
  Owner: { dynamic: "Owner/Pet", match: "Pet", desc: "Playful bond.", longDesc: "Control & care." },
  Rigger: { dynamic: "Bondage Play", match: "Rope Bunny", desc: "Artistic exchange.", longDesc: "Creativity & trust." },
  Sadist: { dynamic: "Sadomasochism", match: "Masochist", desc: "Thrilling exchange.", longDesc: "Pain & pleasure safely." },
  Hunter: { dynamic: "Primal Play", match: "Prey", desc: "Wild chase.", longDesc: "Pursuit fuels bond." },
  Trainer: { dynamic: "Training Play", match: "Puppy", desc: "Structured bond.", longDesc: "Discipline & growth." },
  Puppeteer: { dynamic: "Control Play", match: "Doll", desc: "Creative shaping.", longDesc: "Precision directs." },
  Protector: { dynamic: "Protection Play", match: "Little", desc: "Strong bond.", longDesc: "Care & safety." },
  Disciplinarian: { dynamic: "Discipline Play", match: "Brat", desc: "Lively challenge.", longDesc: "Control & defiance." },
  Caretaker: { dynamic: "Caretaking Play", match: "Little", desc: "Nurturing bond.", longDesc: "Love & exploration." },
  Sir: { dynamic: "Sir/Submissive", match: "Submissive", desc: "Respectful bond.", longDesc: "Honor & obedience." },
  Goddess: { dynamic: "Worship Play", match: "Thrall", desc: "Divine bond.", longDesc: "Adoration & service." },
  Commander: { dynamic: "Command Play", match: "Switch", desc: "Strategic bond.", longDesc: "Control & flexibility." }
};

// Trait weights for scoring
export const sfStyleKeyTraits = {
    'Submissive': ['obedience', 'submissionDepth', 'vulnerability'],
    'Brat': ['rebellion', 'mischief', 'playfulness'],
    'Slave': ['service', 'devotion', 'submissionDepth'],
    'Switch': ['adaptability', 'exploration', 'playfulness'], // Note: Switch scoring might need refinement
    'Pet': ['affection', 'playfulness', 'devotion'],
    'Little': ['innocence', 'dependence', 'affection'],
    'Puppy': ['playfulness', 'devotion', 'affection'],
    'Kitten': ['sensuality', 'mischief', 'affection'],
    'Princess': ['sensuality', 'innocence', 'dependence'],
    'Rope Bunny': ['sensuality', 'exploration', 'submissionDepth'],
    'Masochist': ['painTolerance', 'submissionDepth', 'vulnerability'],
    'Prey': ['exploration', 'vulnerability', 'rebellion'],
    'Toy': ['submissionDepth', 'adaptability', 'service'],
    'Doll': ['vulnerability', 'dependence', 'sensuality'],
    'Bunny': ['playfulness', 'innocence', 'affection'],
    'Servant': ['service', 'obedience', 'devotion'],
    'Playmate': ['playfulness', 'mischief', 'exploration'],
    'Babygirl': ['dependence', 'innocence', 'affection'],
    'Captive': ['submissionDepth', 'vulnerability', 'exploration'],
    'Thrall': ['devotion', 'submissionDepth', 'dependence'],
    'Puppet': ['receptiveness', 'adaptability'],
    'Maid': ['tidiness', 'politeness'],
    'Painslut': ['painTolerance', 'craving'],
    'Bottom': ['receptiveness', 'painTolerance'],
    'Dominant': ['authority', 'confidence', 'leadership'],
    'Assertive': ['boldness', 'intensity', 'authority'],
    'Nurturer': ['care', 'empathy', 'patience'],
    'Strict': ['discipline', 'control', 'precision'],
    'Master': ['authority', 'possession', 'dominanceDepth'],
    'Mistress': ['confidence', 'creativity', 'dominanceDepth'],
    'Daddy': ['care', 'possession', 'empathy'],
    'Mommy': ['care', 'patience', 'empathy'],
    'Owner': ['possession', 'control', 'dominanceDepth'],
    'Rigger': ['creativity', 'precision', 'control'],
    'Sadist': ['sadism', 'intensity', 'control'],
    'Hunter': ['boldness', 'leadership', 'intensity'],
    'Trainer': ['patience', 'discipline', 'leadership'],
    'Puppeteer': ['control', 'creativity', 'precision'],
    'Protector': ['care', 'authority', 'possession'],
    'Disciplinarian': ['discipline', 'authority', 'precision'],
    'Caretaker': ['care', 'empathy', 'patience'],
    'Sir': ['authority', 'confidence', 'leadership'],
    'Goddess': ['confidence', 'intensity', 'dominanceDepth'],
    'Commander': ['authority', 'intensity', 'dominanceDepth']
};
